name: Android CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    #    if: "contains(github.event.head_commit.message, 'ci build android')"
    steps:
      - uses: actions/checkout@v4.2.0
      - name: set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle debug
        run: ./gradlew assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/

      - name: Build with Gradle release
        run: ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/

      - name: Build with Gradle bundle
        run: ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: app-bundle.aab
          path: app/build/outputs/apk/release/